### ISSUE TITLE
Relationship between Trips and Conditions

### ISSUE THREAD

**Issue by corneliusellen** [lnchambers/bay_cycles#89]
@AliSchlereth @icorson3 @lnchambers @Heybluguy 
Hey all, 

I'm starting to look at the weather conditions dashboard and wondering the best way to go about setting up the relationships. 

A trip belongs to a condition and a condition has many trips. Right now, I'm thinking a trip belongs to a condition through TWO columns (zip code and start_date). The problem is I can't have a column on Trips called "Condition ID" which points to two primary keys on Conditions (zip code and date), because this violates the definition of a foreign key.

My other thought was to go about it by creating an AR method on Conditions called def trips, which would be a where clause that takes in a zip code and date parameter and returns a collection of trips.

I might be overcomplicating this. Mainly, I want to know if our schema is okay: http://ondras.zarovi.cz/sql/demo/ (use load bay_cycles). Right now, Conditions is not connected to trips and I don't know how it should be.

**Comment by AliSchlereth** [comment]
@corneliusellen I'd have the foreign key be condition_id which points to the condition's id. In order to make the original association I'd scope it to the zip code and start date. Does that make sense?

**Comment by corneliusellen** [comment]
What do you mean make the original association?

**Comment by AliSchlereth** [comment]
@corneliusellen When you create the relationship between the trip and the condition. This would be in your seed file, or when someone creates a new trip/condition.

**Comment by AliSchlereth** [comment]
@corneliusellen After talking with @icorson3, I think she can give you better direction than I have. She'll post here sometime today.

**Comment by icorson3** [comment]
@corneliusellen I briefly mentioned this in class when a classmate brought it up, so great question! 

You can assume that all conditions exist for just one zipcode so I would pick the first one. At that point, the relationship between condition and trip is date as you already said. I would just use one primary key. Let me know if you have additional questions!

**Comment by corneliusellen** [comment]
Oh! I understand why Matt was asking that question now. Thanks for the clarification, yall! @AliSchlereth @icorson3

**Comment by corneliusellen** [comment]
@icorson3 Would it be a good idea to get rid of the ID primary key on Condition and instead make condition's primary key it's date attribute?

**Comment by icorson3** [comment]
@corneliusellen that is a fine idea...there are pros and cons to both strategies...we are ok if you decide on either route...it is adding an additional column when providing `condition_id` on trip but you have to do a little more work if you go the other direction to get the date to be the primary key

**Comment by corneliusellen** [comment]
@icorson3 awesomesauce, thank you for the input
